# Specify a base image
FROM node:18.17.1

# Set a working directory
WORKDIR /app

# Copy package.json files to the working directory and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application files
COPY . .

# Generate ".env.local" file
# ARG NEXT_PUBLIC_BACKEND_URL
# RUN touch .env.production
# RUN echo "NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL" >> .env.production

# Start a development server
CMD [ "npm", "run", "dev" ]