services:
  frontend:
    image: cab432-mashup-docker-project-frontend-dev
    container_name: cab432-mashup-docker-project-frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    tty: true
    depends_on:
      - backend
    networks:
      - shared-network

  backend:
    image: cab432-mashup-docker-project-backendend-dev
    container_name: cab432-mashup-docker-project-backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
    tty: true
    depends_on:
      - db
    networks:
      - shared-network

  db:
    image: mysql:8.0
    container_name: cab432-mashup-docker-project-db-dev
    ports:
      - 3300:3306
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - shared-network

volumes:
  frontend_node_modules:
  backend_node_modules:
  db-volume:

networks:
  shared-network:
    external: true
