services:
  frontend:
    image: cab432-mashup-docker-project-frontend-prod
    container_name: cab432-mashup-docker-project-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - backend
    networks:
      - shared-network
  
  backend:
    image: cab432-mashup-docker-project-backend-prod
    container_name: cab432-mashup-docker-project-backend-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 8000:8000
    env_file:
      - .env
    tty: true
    depends_on:
      - db
    networks:
      - shared-network
      
  db:
    image: mysql:8.0
    container_name: cab432-mashup-docker-project-db-prod
    ports:
      - 3300:3306
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - shared-network

volumes:
  db-volume:

networks:
  shared-network:
