services:
  frontend:
    image: nextjs-dev
    container_name: nextjs-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - front_node_modules:/app/node_modules
    tty: true
    depends_on:
      - db
    networks:
      - shared-network

  backend:
    image: nodejs-prod
    container_name: nodejs-prod
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - 5000:5000
    env_file:
      - .env
    tty: true
    networks:
      - shared-network

  db:
    image: mysql:8.0
    container_name: mysql-dev
    ports:
      - 3300:3306
    env_file:
      - .env
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - shared-network

volumes:
  front_node_modules:
  db-volume:

networks:
  shared-network:
    external: true
